import { Router } from "express";
import { institutionRouter, institutionConfigRouter } from "./institution.routes";
import { studentIdRouter } from "./student-id.routes";
import { gradingRouter } from "./grading.routes";
import { examTypesRouter } from "./exam-types.routes";
import { feeRulesRouter } from "./fee-rules.routes";
import { attendanceRulesRouter } from "./attendance-rules.routes";
import { signaturesRouter, authorityConfigRouter } from "./signatures.routes";
import { templatesRouter } from "./templates.routes";
import { notificationsRouter } from "./notifications.routes";
import { academicYearsRouter, shiftsRouter, departmentsRouter, classesRouter, sectionsRouter, groupsRouter, routineRouter, routineSubstitutionsRouter } from "./academic.routes";
import { programsRouter, coursesRouter } from "./university.routes";
import { usersRouter } from "./users.routes";
import { auditLogRouter } from "./audit-log.routes";
import { permissionsRouter } from "./permissions.routes";
import { paymentGatewaysRouter } from "./payment-gateways.routes";
import { marksheetDisplayRouter } from "./marksheet-display.routes";

export const settingsRouter = Router();

settingsRouter.use("/institution", institutionRouter);
settingsRouter.use("/config", institutionConfigRouter);
settingsRouter.use("/student-id-config", studentIdRouter);
settingsRouter.use("/grading-scales", gradingRouter);
settingsRouter.use("/exam-types", examTypesRouter);
settingsRouter.use("/fee-rules", feeRulesRouter);
settingsRouter.use("/attendance-rules", attendanceRulesRouter);
settingsRouter.use("/signatures", signaturesRouter);
settingsRouter.use("/authority-config", authorityConfigRouter);
settingsRouter.use("/templates", templatesRouter);
settingsRouter.use("/notifications", notificationsRouter);
settingsRouter.use("/academic-years", academicYearsRouter);
settingsRouter.use("/shifts", shiftsRouter);
settingsRouter.use("/departments", departmentsRouter);
settingsRouter.use("/classes", classesRouter);
settingsRouter.use("/sections", sectionsRouter);
settingsRouter.use("/groups", groupsRouter);
settingsRouter.use("/routine", routineRouter);
settingsRouter.use("/routine/substitutions", routineSubstitutionsRouter);
settingsRouter.use("/programs", programsRouter);
settingsRouter.use("/courses", coursesRouter);
settingsRouter.use("/users", usersRouter);
settingsRouter.use("/audit-log", auditLogRouter);
settingsRouter.use("/permissions", permissionsRouter);
settingsRouter.use("/payment-gateways", paymentGatewaysRouter);
settingsRouter.use("/marksheet-display", marksheetDisplayRouter);
