import type { UserRole } from "@education-erp/types";

// Mirrors CLAUDE.md's Permission Matrix table.
export const SETTINGS_INSTITUTION_ROLES: UserRole[] = ["ADMIN", "IT_ADMIN"];
export const SETTINGS_ACADEMIC_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER"];
export const SETTINGS_USERS_ROLES: UserRole[] = ["ADMIN", "IT_ADMIN"];
export const STUDENT_CRUD_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "REGISTRAR"];
export const STUDENT_PROMOTE_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER"];
export const STAFF_READ_ROLES: UserRole[] = [
  "ADMIN", "PRINCIPAL", "VICE_PRINCIPAL", "EXAM_CONTROLLER", "HEAD_OF_DEPT",
  "CLASS_TEACHER", "SUBJECT_TEACHER", "ACCOUNTANT", "LIBRARIAN", "TRANSPORT_MANAGER",
  "HOSTEL_MANAGER", "PROCTOR", "REGISTRAR", "IT_ADMIN",
];
export const ATTENDANCE_MARK_ROLES: UserRole[] = ["ADMIN", "CLASS_TEACHER", "SUBJECT_TEACHER"];
export const EXAM_MANAGE_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER"];
export const MARK_ENTRY_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER", "SUBJECT_TEACHER"];
export const MARK_APPROVAL_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER"];
export const RESULT_PUBLISH_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER"];
export const FEE_COLLECTION_ROLES: UserRole[] = ["ADMIN", "ACCOUNTANT"];
export const ADMISSION_MANAGE_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "EXAM_CONTROLLER"];
export const ADMISSION_ENROLL_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL"];
export const WEBSITE_CONTENT_ROLES: UserRole[] = ["ADMIN", "PRINCIPAL", "IT_ADMIN"];
